// ─── Display Tuning Module ──────────────────────────────────────────────────
// Derived from PC-Tuning display-tuning and gaming-optimization skills.

import type { TuningActionDefinition } from "../types.js";

export const displayActions: TuningActionDefinition[] = [
  {
    id: "display.disable-pointer-acceleration",
    name: "Disable Mouse Pointer Acceleration",
    category: "display",
    description: "Disable Windows pointer acceleration (Enhance Pointer Precision) by setting MouseSpeed, MouseThreshold1, and MouseThreshold2 to 0.",
    rationale: "Pointer acceleration applies a non-linear multiplier to mouse movement based on speed, making precise aiming inconsistent in games. Setting all acceleration thresholds to 0 creates a 1:1 mapping between physical mouse movement and cursor movement, essential for building consistent muscle memory in FPS games.",
    tier: "free",
    risk: "safe",
    compatibility: {},
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "mouse_input_linearity",
      directionBetter: "higher",
      estimatedDelta: "1:1 mouse movement (eliminates variable acceleration curve)",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_CURRENT_USER",
        path: "Control Panel\\Mouse",
        valueName: "MouseSpeed",
        valueType: "REG_SZ",
        newValue: "0",
      },
      {
        hive: "HKEY_CURRENT_USER",
        path: "Control Panel\\Mouse",
        valueName: "MouseThreshold1",
        valueType: "REG_SZ",
        newValue: "0",
      },
      {
        hive: "HKEY_CURRENT_USER",
        path: "Control Panel\\Mouse",
        valueName: "MouseThreshold2",
        valueType: "REG_SZ",
        newValue: "0",
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Desktop mouse movement may feel different if previously relying on acceleration"],
    tags: ["input", "mouse", "gaming", "latency"],
  },
  {
    id: "display.disable-transparency",
    name: "Disable Transparency Effects",
    category: "display",
    description: "Disable Windows transparency and blur effects (acrylic, Mica) in the desktop compositor.",
    rationale: "Transparency effects require the DWM compositor to perform additional blending passes for taskbar, Start menu, and window chrome. Disabling eliminates these GPU compositor cycles, freeing GPU resources for the game and reducing DWM frame time.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 10240 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "dwm_compositor_overhead",
      directionBetter: "lower",
      estimatedDelta: "Reduces DWM GPU usage by ~1-3%",
      confidence: "estimated",
    },
    registryChanges: [
      {
        hive: "HKEY_CURRENT_USER",
        path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize",
        valueName: "EnableTransparency",
        valueType: "REG_DWORD",
        newValue: 0,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Taskbar, Start menu, and window chrome will appear opaque"],
    tags: ["display", "compositor", "performance", "visual"],
  },
  {
    id: "display.disable-game-bar",
    name: "Disable Game Bar and Game DVR",
    category: "display",
    description: "Disable the Xbox Game Bar overlay and Game DVR background recording, removing the capture pipeline from the display path.",
    rationale: "Game Bar injects a capture hook into every DirectX application, and Game DVR maintains a background recording buffer consuming GPU encode resources. Disabling both removes the overlay injection and stops background H.264/HEVC encoding, reducing GPU overhead and eliminating Game Bar-induced frame time spikes.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 10240 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "gpu_encode_overhead",
      directionBetter: "lower",
      estimatedDelta: "Eliminates background DVR encoding (~2-5% GPU on supported hardware)",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_CURRENT_USER",
        path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\GameDVR",
        valueName: "AppCaptureEnabled",
        valueType: "REG_DWORD",
        newValue: 0,
      },
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Policies\\Microsoft\\Windows\\GameDVR",
        valueName: "AllowGameDVR",
        valueType: "REG_DWORD",
        newValue: 0,
      },
      {
        hive: "HKEY_CURRENT_USER",
        path: "System\\GameConfigStore",
        valueName: "GameDVR_Enabled",
        valueType: "REG_DWORD",
        newValue: 0,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [
      "Cannot use Game Bar overlay (Win+G) for screenshots or recording",
      "Game Bar FPS counter and performance overlay will not be available",
    ],
    tags: ["display", "gaming", "debloat", "performance"],
  },
  {
    id: "display.disable-sticky-keys",
    name: "Disable Sticky Keys Prompt",
    category: "display",
    description: "Disable the 'Turn on Sticky Keys?' prompt triggered by pressing Shift 5 times, preventing accidental activation during gaming.",
    rationale: "The Sticky Keys accessibility shortcut activates when Shift is pressed 5 times in quick succession — a common occurrence in FPS games using Shift for sprint. The prompt steals focus from the game, causing a loss of input and potential death in competitive scenarios.",
    tier: "free",
    risk: "safe",
    compatibility: {},
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      {
        hive: "HKEY_CURRENT_USER",
        path: "Control Panel\\Accessibility\\StickyKeys",
        valueName: "Flags",
        valueType: "REG_SZ",
        newValue: "506",
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Sticky Keys shortcut (5x Shift) will no longer work"],
    tags: ["display", "gaming", "accessibility", "input"],
  },
];
