// Storage Tuning Module
// Derived from the redcore internal storage-optimization notes.

import type { TuningActionDefinition } from "../types.js";

export const storageActions: TuningActionDefinition[] = [
  {
    id: "storage.disable-last-access",
    name: "Disable NTFS Last Access Timestamp",
    category: "storage",
    description: "Disable updating the last access timestamp on files and directories, reducing write I/O for every file read operation.",
    rationale: "By default, NTFS updates the LastAccessTime metadata on every file read. For gaming workloads that read thousands of asset files, this generates substantial unnecessary write I/O. Windows 10 1803+ defaults to 'User Managed' (disabled for user-mode reads) but this ensures it is explicitly disabled system-wide via NtfsDisableLastAccessUpdate.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "filesystem_write_io",
      directionBetter: "lower",
      estimatedDelta: "Reduces metadata write I/O on every file read",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Control\\FileSystem",
        valueName: "NtfsDisableLastAccessUpdate",
        valueType: "REG_DWORD",
        newValue: 0x80000003,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Backup software relying on last access time may not detect accessed files"],
    tags: ["storage", "filesystem", "ntfs", "performance"],
  },
  {
    id: "storage.enable-write-caching",
    name: "Enable Disk Write Caching",
    category: "storage",
    description: "Enable write caching on storage devices, allowing the OS to buffer writes in RAM before flushing to disk for improved I/O throughput.",
    rationale: "Write caching allows the storage driver to acknowledge writes before they reach the physical media, dramatically improving random write performance. This is critical for game shader caches, save files, and config writes. On NVMe/SSD with capacitors or UPS, the risk of data loss from power failure is minimal.",
    tier: "free",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "random_write_latency",
      directionBetter: "lower",
      estimatedDelta: "2-10x improvement in random write throughput",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Enum\\SCSI\\<device>\\<instance>\\Device Parameters\\Disk",
        valueName: "UserWriteCacheSetting",
        valueType: "REG_DWORD",
        newValue: 1,
      },
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Enum\\SCSI\\<device>\\<instance>\\Device Parameters\\Disk",
        valueName: "CacheIsPowerProtected",
        valueType: "REG_DWORD",
        newValue: 1,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Risk of data loss if power is lost during a write (mitigated by UPS or SSD capacitors)"],
    tags: ["storage", "write-cache", "performance"],
  },
  {
    id: "storage.disable-indexing",
    name: "Disable Windows Search Indexing Service",
    category: "storage",
    description: "Disable the Windows Search indexing service (WSearch) which continuously scans and indexes file contents in the background.",
    rationale: "The Windows Search indexer consumes disk I/O, CPU, and memory by continuously crawling files for content indexing. For gaming systems where fast file search is not a priority, disabling it eliminates background I/O contention that can cause micro-stutter during gameplay.",
    tier: "free",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "background_disk_io",
      directionBetter: "lower",
      estimatedDelta: "Eliminates indexer I/O spikes (can be 10-50 MB/s during indexing)",
      confidence: "measured",
    },
    registryChanges: [],
    serviceChanges: [
      { serviceName: "WSearch", newStartType: "Disabled" },
    ],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [
      "Windows Search and Start menu file search will be significantly slower",
      "Outlook desktop search will not work without indexing",
    ],
    tags: ["storage", "debloat", "performance", "service"],
  },
  {
    id: "storage.disable-8dot3-filenames",
    name: "Disable 8.3 Short Filename Creation",
    category: "storage",
    description: "Disable creation of legacy 8.3-character (DOS-compatible) short filenames on NTFS volumes, reducing directory enumeration overhead.",
    rationale: "NTFS creates a legacy 8.3 short filename entry for every file for DOS compatibility. This doubles the number of directory entries, slowing directory enumeration and file creation operations. On modern Windows systems, 8.3 names serve no purpose and their generation adds measurable overhead to file-heavy workloads like game loading, shader compilation, and build systems.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "directory_enumeration_speed",
      directionBetter: "higher",
      estimatedDelta: "Reduces directory entry count by ~50%, faster file operations",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Control\\FileSystem",
        valueName: "NtfsDisable8dot3NameCreation",
        valueType: "REG_DWORD",
        newValue: 1,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: true,
    sideEffects: [
      "Very old applications expecting 8.3 filenames may fail (extremely rare on modern systems)",
      "Only prevents creation of new 8.3 names; existing ones remain",
    ],
    tags: ["storage", "filesystem", "ntfs", "performance"],
  },
];
