// CPU Tuning Module
// Derived from the redcore internal CPU-optimization notes.

import type { TuningActionDefinition } from "../types.js";

export const cpuActions: TuningActionDefinition[] = [
  {
    id: "cpu.win32-priority-separation",
    name: "Win32PrioritySeparation → 0x26 (Gaming)",
    category: "cpu",
    description: "Set scheduler to Short, Variable quantum with 2:1 foreground boost. Gives foreground threads (your game) short but frequent time slices with priority over background tasks.",
    rationale: "Windows default is 0x02 (Short, Variable, 3:1 on client). 0x26 (38 decimal) provides optimal gaming responsiveness per kernel debugger analysis. The 2:1 foreground boost via PsPrioritySeparation also affects wait completion priority boosts.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "scheduler_responsiveness",
      directionBetter: "higher",
      estimatedDelta: "Measurable in frame-time consistency",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Control\\PriorityControl",
        valueName: "Win32PrioritySeparation",
        valueType: "REG_DWORD",
        newValue: 0x26,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Background tasks get relatively less CPU time"],
    tags: ["scheduler", "gaming", "latency"],
  },
  {
    id: "cpu.disable-core-parking",
    name: "Disable CPU Core Parking",
    category: "cpu",
    description: "Set minimum processor cores to 100% on AC power, preventing Windows from parking cores during low load. Parked cores introduce 1–5 ms wake latency whenever a workload needs more threads.",
    rationale: "Core parking powers down unused cores to save energy, but causes micro-stutter when a game suddenly needs more threads and the OS must unpark them (1–5 ms wake latency). On a desktop plugged into AC power, core parking provides no meaningful benefit and only adds latency jitter.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "core_wake_latency",
      directionBetter: "lower",
      estimatedDelta: "Eliminates 1–5 ms parking wake latency",
      confidence: "measured",
    },
    registryChanges: [],
    serviceChanges: [],
    powerChanges: [
      { settingPath: "54533251-82be-4824-96c1-47b60b740d00/0cc5b647-c1df-4637-891a-dec35c318583", newValue: "100" },
    ],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [
      "Higher idle power consumption (~5–15 W on a desktop system)",
      "All CPU cores remain active even during idle periods",
      "Not recommended for laptops on battery power",
    ],
    tags: ["cpu", "parking", "latency", "gaming"],
  },
  {
    id: "cpu.aggressive-boost-mode",
    name: "Aggressive Processor Boost Mode",
    category: "cpu",
    description: "Set processor performance boost policy to Aggressive (mode 2). This prioritizes sustained maximum turbo frequency over power efficiency.",
    rationale: "Default boost mode may downscale frequency under sustained load to save power. Aggressive mode tells the OS to keep boosting as long as thermal and power limits allow.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "sustained_clock_speed",
      directionBetter: "higher",
      estimatedDelta: "~100-300 MHz higher sustained boost",
      confidence: "estimated",
    },
    registryChanges: [],
    serviceChanges: [],
    powerChanges: [
      { settingPath: "54533251-82be-4824-96c1-47b60b740d00/be337238-0d82-4146-a960-4f3749d470c7", newValue: "2" },
    ],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [
      "Higher temperatures under sustained load",
      "Increased power consumption",
      "May cause thermal throttling on inadequate cooling",
    ],
    tags: ["cpu", "performance", "boost", "gaming"],
  },
  {
    id: "cpu.min-processor-state-100",
    name: "Set Minimum Processor State to 100%",
    category: "cpu",
    description: "Prevent the CPU from throttling below maximum frequency. Sets both minimum and maximum processor state to 100%.",
    rationale: "When min processor state is below 100%, the CPU may reduce its frequency during brief idle moments, causing frame time spikes. Setting to 100% keeps the CPU at full speed.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "cpu_frequency_consistency",
      directionBetter: "higher",
      estimatedDelta: "Eliminates frequency scaling latency",
      confidence: "measured",
    },
    registryChanges: [],
    serviceChanges: [],
    powerChanges: [
      { settingPath: "54533251-82be-4824-96c1-47b60b740d00/893dee8e-2bef-41e0-89c6-b55d0929964c", newValue: "100" },
      { settingPath: "54533251-82be-4824-96c1-47b60b740d00/bc5038f7-23e0-4960-96da-33abaf5935ec", newValue: "100" },
    ],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [
      "CPU runs at maximum frequency at all times",
      "Significantly higher idle power and heat",
      "Not recommended for laptops",
    ],
    tags: ["cpu", "power", "frequency", "gaming"],
  },
  {
    id: "cpu.disable-dynamic-tick",
    name: "Disable Dynamic Tick and Enable Platform Timer",
    category: "cpu",
    description: "Disable the Windows dynamic tick mechanism via BCD, forcing a fixed timer interrupt interval. Enable the platform hardware timer (HPET/TSC) as the tick source to provide the lowest possible timer jitter.",
    rationale: "Dynamic tick (tickless kernel) allows Windows to skip timer interrupts during idle periods to save power. This creates variable timer resolution that can cause micro-stutter in latency-sensitive workloads. Disabling dynamic tick forces consistent timer interrupts. `useplatformtick` ensures the platform hardware timer (HPET or TSC) is used as the tick source instead of the synthetic timer, providing the lowest possible timer jitter. redcore lab testing identifies this as one of the highest-impact latency tweaks alongside GlobalTimerResolutionRequests.",
    tier: "premium",
    risk: "medium",
    compatibility: { minBuild: 9200 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "timer_consistency",
      directionBetter: "higher",
      estimatedDelta: "Eliminates timer coalescing jitter (up to 15 ms variance)",
      confidence: "measured",
    },
    registryChanges: [],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [
      { element: "disabledynamictick", newValue: "yes" },
      { element: "useplatformtick", newValue: "yes" },
    ],
    requiresReboot: true,
    sideEffects: [
      "Higher idle power consumption due to fixed timer interrupts",
      "CPU never enters deepest idle C-states",
      "Not recommended for laptops on battery power",
    ],
    tags: ["cpu", "timer", "latency", "gaming", "bcd"],
  },
  {
    id: "cpu.global-timer-resolution",
    name: "Enable Global Timer Resolution Requests",
    category: "cpu",
    description: "Set the GlobalTimerResolutionRequests registry key to restore system-wide timer resolution behavior on Windows 11+.",
    rationale: "Starting with Windows 10 2004, timer resolution requests became per-process instead of global. This means a game requesting 0.5ms timer resolution no longer benefits the entire system. The GlobalTimerResolutionRequests registry key (Windows 11+ / Server 2022+) restores the pre-2004 global behavior, allowing one application's timer request to benefit all processes.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 22000 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "system_timer_precision",
      directionBetter: "higher",
      estimatedDelta: "Sleep(1) achieves ~1.5ms precision vs ~15.6ms default",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\kernel",
        valueName: "GlobalTimerResolutionRequests",
        valueType: "REG_DWORD",
        newValue: 1,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: true,
    sideEffects: [
      "Any process requesting high timer resolution will affect all processes system-wide",
      "Slightly higher idle power consumption",
    ],
    tags: ["cpu", "timer", "latency", "gaming", "windows11"],
  },
];
