// Service & Scheduled Task Optimization Module
// Derived from the redcore internal service cleanup research set.
// Every service change is rollback-safe via the service snapshot system.

import type { TuningActionDefinition } from "../types.js";

export const servicesActions: TuningActionDefinition[] = [
  {
    id: "services.disable-sysmain",
    name: "Disable SysMain (Superfetch)",
    category: "services",
    description: "Disable the SysMain service (formerly Superfetch) which preloads frequently used applications into memory.",
    rationale: "SysMain uses background I/O to preload application data into RAM. On systems with an SSD, the preloading offers negligible benefit since SSD read latency is already low (~0.1ms). The background I/O creates disk contention and memory pressure that can cause frame time spikes during gaming. On HDD systems, SysMain is beneficial and should remain enabled.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 10240 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "background_disk_io",
      directionBetter: "lower",
      estimatedDelta: "Eliminates Superfetch I/O spikes (5-50 MB/s during prefetch)",
      confidence: "measured",
    },
    registryChanges: [],
    serviceChanges: [
      { serviceName: "SysMain", newStartType: "Disabled" },
    ],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [
      "Application cold-start may be slightly slower on systems with HDDs",
      "Negligible impact on SSD-based systems",
      "Memory compression features are also disabled",
    ],
    tags: ["services", "performance", "disk", "memory"],
  },
  {
    id: "services.disable-xbox-services",
    name: "Disable Xbox Background Services",
    category: "services",
    description: "Disable Xbox-related background services: Xbox Accessory Management, Xbox Live Auth, Xbox Live Game Save, and Xbox Live Networking.",
    rationale: "Xbox services run in the background even when no Xbox features are used. They maintain persistent network connections, handle game save synchronization, and manage Xbox accessories. For users not using Xbox Game Pass, Xbox Live, or Xbox controllers, these services consume resources without benefit.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 10240 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "background_service_count",
      directionBetter: "lower",
      estimatedDelta: "Eliminates 4 background services and their network connections",
      confidence: "measured",
    },
    registryChanges: [],
    serviceChanges: [
      { serviceName: "XblAuthManager", newStartType: "Disabled" },
      { serviceName: "XblGameSave", newStartType: "Disabled" },
      { serviceName: "XboxNetApiSvc", newStartType: "Disabled" },
      { serviceName: "XboxGipSvc", newStartType: "Disabled" },
    ],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [
      "Xbox Game Pass cloud saves will not sync",
      "Xbox Live features will not work",
      "Xbox Wireless Controller may lose some features",
    ],
    tags: ["services", "debloat", "xbox", "gaming"],
  },
  {
    id: "services.disable-print-spooler",
    name: "Disable Print Spooler",
    category: "services",
    description: "Disable the Print Spooler service which manages print queues. Safe to disable on gaming systems with no printers.",
    rationale: "The Print Spooler service loads multiple DLLs and runs background threads even when no printer is configured. It has been the target of multiple critical security vulnerabilities (PrintNightmare CVE-2021-34527). Disabling it eliminates both the security attack surface and the background resource usage.",
    tier: "free",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "attack_surface_reduction",
      directionBetter: "lower",
      estimatedDelta: "Eliminates PrintNightmare attack vector + background thread overhead",
      confidence: "measured",
    },
    registryChanges: [],
    serviceChanges: [
      { serviceName: "Spooler", newStartType: "Disabled" },
    ],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [
      "Cannot print from this system — re-enable if a printer is connected",
      "Print-to-PDF will not work",
    ],
    tags: ["services", "security", "debloat"],
  },
  {
    id: "services.disable-remote-services",
    name: "Disable Remote Access Services",
    category: "services",
    description: "Disable Remote Desktop, Remote Registry, and Remote Assistance services that allow external connections to this PC.",
    rationale: "Remote access services listen for incoming connections and maintain authentication state. On a dedicated gaming PC, these services represent unnecessary attack surface and background resource usage. Disabling them hardens the system and frees resources.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Control\\Remote Assistance",
        valueName: "fAllowToGetHelp",
        valueType: "REG_DWORD",
        newValue: 0,
      },
    ],
    serviceChanges: [
      { serviceName: "RemoteRegistry", newStartType: "Disabled" },
      { serviceName: "TermService", newStartType: "Disabled" },
      { serviceName: "SessionEnv", newStartType: "Disabled" },
    ],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [
      "Cannot use Remote Desktop to connect to this PC",
      "Remote Registry access will be denied",
      "Remote Assistance invitations cannot be sent or accepted",
    ],
    tags: ["services", "security", "hardening"],
  },
];
