// ─── AI Feature Control Module ──────────────────────────────────────────────
// Disables Windows AI features: Recall, Click to Do, Edge AI, Paint AI, Notepad AI.
// Sourced from Win11Debloat feature analysis.

import type { TuningActionDefinition } from "../types.js";

export const aiActions: TuningActionDefinition[] = [
  {
    id: "ai.disable-recall",
    name: "Disable Windows Recall",
    category: "privacy",
    description: "Disable the Windows Recall AI feature that captures screen activity snapshots.",
    rationale: "Recall continuously screenshots your activity for AI search. Disabling protects privacy and saves storage.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 26100 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      { hive: "HKEY_CURRENT_USER", path: "Software\\Policies\\Microsoft\\Windows\\WindowsAI", valueName: "DisableAIDataAnalysis", valueType: "REG_DWORD", newValue: 1 },
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsAI", valueName: "DisableAIDataAnalysis", valueType: "REG_DWORD", newValue: 1 },
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsAI", valueName: "AllowRecallEnablement", valueType: "REG_DWORD", newValue: 0 },
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsAI", valueName: "TurnOffSavingSnapshots", valueType: "REG_DWORD", newValue: 1 },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Recall feature will be completely disabled"],
    tags: ["privacy", "ai", "recall"],
  },
  {
    id: "ai.disable-click-to-do",
    name: "Disable Click to Do",
    category: "privacy",
    description: "Disable the AI-powered Click to Do overlay that analyzes on-screen content.",
    rationale: "Click to Do uses AI to analyze visible content and suggest actions. Disabling prevents AI screen analysis.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 26100 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsAI", valueName: "DisableClickToDo", valueType: "REG_DWORD", newValue: 1 },
      { hive: "HKEY_CURRENT_USER", path: "Software\\Policies\\Microsoft\\Windows\\WindowsAI", valueName: "DisableClickToDo", valueType: "REG_DWORD", newValue: 1 },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [],
    tags: ["privacy", "ai"],
  },
  {
    id: "ai.disable-ai-service",
    name: "Prevent AI Service Auto Start",
    category: "privacy",
    description: "Set Windows AI Fabric service to manual startup instead of automatic.",
    rationale: "WSAIFabricSvc starts automatically and consumes resources for AI features most users don't use.",
    tier: "free",
    risk: "safe",
    compatibility: {},
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      { hive: "HKEY_LOCAL_MACHINE", path: "SYSTEM\\CurrentControlSet\\Services\\WSAIFabricSvc", valueName: "Start", valueType: "REG_DWORD", newValue: 3 },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["AI features may take longer to initialize when used"],
    tags: ["privacy", "ai", "performance"],
  },
  {
    id: "ai.disable-edge-ai",
    name: "Disable Edge AI Features",
    category: "privacy",
    description: "Disable Copilot sidebar, AI search, compose inline, and other AI features in Microsoft Edge.",
    rationale: "Edge AI features send browsing context and content to cloud AI services.",
    tier: "free",
    risk: "safe",
    compatibility: {},
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Policies\\Microsoft\\Edge", valueName: "HubsSidebarEnabled", valueType: "REG_DWORD", newValue: 0 },
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Policies\\Microsoft\\Edge", valueName: "CopilotCDPPageContext", valueType: "REG_DWORD", newValue: 0 },
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Policies\\Microsoft\\Edge", valueName: "CopilotPageContext", valueType: "REG_DWORD", newValue: 0 },
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Policies\\Microsoft\\Edge", valueName: "EdgeHistoryAISearchEnabled", valueType: "REG_DWORD", newValue: 0 },
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Policies\\Microsoft\\Edge", valueName: "ComposeInlineEnabled", valueType: "REG_DWORD", newValue: 0 },
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Policies\\Microsoft\\Edge", valueName: "NewTabPageBingChatEnabled", valueType: "REG_DWORD", newValue: 0 },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Edge AI sidebar and Copilot integration will be disabled"],
    tags: ["privacy", "ai", "edge"],
  },
  {
    id: "ai.disable-paint-ai",
    name: "Disable Paint AI Features",
    category: "privacy",
    description: "Disable AI-powered Cocreator, Image Creator, and generative tools in Paint.",
    rationale: "Paint AI features send image data to cloud for AI processing.",
    tier: "free",
    risk: "safe",
    compatibility: {},
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Paint", valueName: "DisableCocreator", valueType: "REG_DWORD", newValue: 1 },
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Paint", valueName: "DisableImageCreator", valueType: "REG_DWORD", newValue: 1 },
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Paint", valueName: "DisableGenerativeFill", valueType: "REG_DWORD", newValue: 1 },
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Paint", valueName: "DisableGenerativeErase", valueType: "REG_DWORD", newValue: 1 },
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Paint", valueName: "DisableRemoveBackground", valueType: "REG_DWORD", newValue: 1 },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Paint AI Cocreator and generative features will be unavailable"],
    tags: ["privacy", "ai", "paint"],
  },
  {
    id: "ai.disable-notepad-ai",
    name: "Disable Notepad AI Features",
    category: "privacy",
    description: "Disable AI-powered text generation and rewriting in Notepad.",
    rationale: "Notepad AI sends text content to cloud for AI processing.",
    tier: "free",
    risk: "safe",
    compatibility: {},
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Policies\\WindowsNotepad", valueName: "DisableAIFeatures", valueType: "REG_DWORD", newValue: 1 },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Notepad AI rewrite and generation features will be unavailable"],
    tags: ["privacy", "ai", "notepad"],
  },
];
