// Memory Tuning Module
// Derived from the redcore internal memory-optimization notes.

import type { TuningActionDefinition } from "../types.js";

export const memoryActions: TuningActionDefinition[] = [
  {
    id: "memory.disable-pagefile",
    name: "Disable Paging File (32 GB+ Systems)",
    category: "memory",
    description: "Disable the Windows paging file entirely. Only safe on systems with 32 GB+ RAM that do not require kernel crash dumps.",
    rationale: "The paging file causes random I/O when memory pressure triggers page-outs, introducing latency spikes during gaming. On systems with 32 GB+ RAM, the pagefile is rarely used and disabling it eliminates paging I/O entirely. Note: some applications and crash dump analysis require a pagefile.",
    tier: "premium",
    risk: "medium",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "paging_io_latency",
      directionBetter: "lower",
      estimatedDelta: "Eliminates page-out I/O stalls completely",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management",
        valueName: "PagingFiles",
        valueType: "REG_MULTI_SZ",
        newValue: [],
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: true,
    sideEffects: [
      "Kernel crash dumps (BSOD analysis) will not be available",
      "Applications that require a pagefile may fail to launch",
      "Systems with less than 32 GB RAM may become unstable under heavy load",
    ],
    tags: ["memory", "latency", "gaming", "advanced"],
  },
  {
    id: "memory.large-pages",
    name: "Enable Large Pages (SeLockMemoryPrivilege)",
    category: "memory",
    description: "Grant the current user the SeLockMemoryPrivilege, enabling applications to request 2 MB large pages instead of 4 KB standard pages.",
    rationale: "Large pages (2 MB on x64) reduce TLB (Translation Lookaside Buffer) misses significantly for memory-intensive games like CS2, Rust, and Escape from Tarkov. Fewer TLB misses means less time spent on virtual-to-physical address translation, improving frame times.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "tlb_miss_rate",
      directionBetter: "lower",
      estimatedDelta: "Up to 10-30% fewer TLB misses in supported applications",
      confidence: "measured",
    },
    registryChanges: [],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: true,
    sideEffects: [
      "Requires user to be added to 'Lock pages in memory' security policy",
      "Applications must explicitly request large pages to benefit",
      "Memory fragmentation over time may reduce large page availability",
    ],
    tags: ["memory", "latency", "gaming", "tlb"],
  },
  {
    id: "memory.disable-compression",
    name: "Disable Memory Compression",
    category: "memory",
    description: "Disable the Windows memory compression agent that compresses in-memory pages to fit more data in RAM, trading CPU cycles for capacity.",
    rationale: "Memory compression uses CPU cycles to compress and decompress pages in the modified page list. On systems with ample RAM (16 GB+), the compression overhead is unnecessary and can cause micro-stutter when the compression thread competes with game threads for CPU time.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 10240 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "cpu_overhead",
      directionBetter: "lower",
      estimatedDelta: "Eliminates compression CPU spikes (~1-3% CPU reduction under memory pressure)",
      confidence: "estimated",
    },
    registryChanges: [],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: true,
    sideEffects: [
      "Higher physical memory usage since pages are stored uncompressed",
      "Systems with less than 16 GB RAM may hit memory pressure sooner",
    ],
    tags: ["memory", "cpu", "latency", "gaming"],
  },
];
