// Network Tuning Module
// Derived from the redcore internal network-optimization notes.

import type { TuningActionDefinition } from "../types.js";

export const networkActions: TuningActionDefinition[] = [
  {
    id: "network.rss-queues-2",
    name: "Set RSS Queues to 2",
    category: "network",
    description: "Configure Receive Side Scaling to use 2 RSS queues, distributing NIC interrupt processing across 2 CPU cores without over-allocating.",
    rationale: "RSS distributes NIC interrupt processing across multiple CPU cores. For typical online gaming (~300 KB/s), 1-2 queues is sufficient per research findings. Over-allocating RSS queues wastes CPU resources that could serve DPCs for the game process. Base processor should not be CPU 0 to avoid contention with OS/DPC processing.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "network_interrupt_distribution",
      directionBetter: "higher",
      estimatedDelta: "Optimal interrupt distribution without CPU waste",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Control\\Class\\{4d36e972-e325-11ce-bfc1-08002be10318}\\<Adapter Index>",
        valueName: "*NumRssQueues",
        valueType: "REG_DWORD",
        newValue: 2,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["High-bandwidth transfers (downloads) may be slightly slower than with more queues"],
    tags: ["network", "rss", "latency", "gaming"],
  },
  {
    id: "network.disable-nagle",
    name: "Disable Nagle's Algorithm (TCPNoDelay)",
    category: "network",
    description: "Disable Nagle's algorithm and set TCP acknowledgement frequency to 1, sending small packets immediately instead of buffering them.",
    rationale: "Nagle's algorithm buffers small TCP packets to reduce overhead, but introduces up to 200ms of delay for small game packets. Disabling it via TCPNoDelay and setting TcpAckFrequency to 1 ensures game state updates are transmitted immediately, reducing network round-trip time for online games.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "tcp_packet_latency",
      directionBetter: "lower",
      estimatedDelta: "Up to 200ms reduction in small packet delivery time",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\\<Interface GUID>",
        valueName: "TcpAckFrequency",
        valueType: "REG_DWORD",
        newValue: 1,
      },
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\\<Interface GUID>",
        valueName: "TCPNoDelay",
        valueType: "REG_DWORD",
        newValue: 1,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Slightly higher network overhead from more frequent small packets"],
    tags: ["network", "latency", "tcp", "gaming"],
  },
  {
    id: "network.tcp-autotuning-normal",
    name: "Set TCP Auto-Tuning to Normal",
    category: "network",
    description: "Ensure TCP receive window auto-tuning is active and window scaling (RFC 1323) is enabled. Sets Tcp1323Opts=1 to enable large window scaling, allowing Windows to dynamically grow the receive buffer up to 16 MB for high-bandwidth connections.",
    rationale: "Some guides recommend disabling TCP window scaling or setting autotuninglevel=disabled, which hard-caps the receive window at 64 KB regardless of bandwidth-delay product. Tcp1323Opts=1 ensures RFC 1323 window scaling is active at the registry level. This complements the netsh autotuninglevel=normal setting and ensures the TCP stack can operate at full receive-window capacity. The 'normal' auto-tuning level is optimal for both gaming and file transfers.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "tcp_throughput",
      directionBetter: "higher",
      estimatedDelta: "Ensures optimal TCP window scaling (vs disabled which caps at 64KB)",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters",
        valueName: "Tcp1323Opts",
        valueType: "REG_DWORD",
        newValue: 1,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [],
    tags: ["network", "tcp", "throughput"],
  },
];
