// GPU Tuning Module
// Derived from the redcore internal GPU-optimization notes.

import type { TuningActionDefinition } from "../types.js";

export const gpuActions: TuningActionDefinition[] = [
  {
    id: "gpu.disable-hags",
    name: "Disable Hardware-Accelerated GPU Scheduling (HAGS)",
    category: "gpu",
    description: "Disable HAGS by setting HwSchMode to 1. HAGS moves GPU scheduling from the CPU to the GPU itself, but can hurt frame time consistency on many systems.",
    rationale: "HAGS improves frame time consistency on some systems but worsens it on others. Disabling provides more predictable behavior. Benchmark with and without on your specific hardware before committing.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 19041 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "frame_time_consistency",
      directionBetter: "higher",
      estimatedDelta: "System-dependent; eliminates HAGS-induced stutter on affected systems",
      confidence: "estimated",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers",
        valueName: "HwSchMode",
        valueType: "REG_DWORD",
        newValue: 1,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: true,
    sideEffects: ["Games that benefit from HAGS may see slightly higher CPU overhead"],
    tags: ["gpu", "latency", "gaming", "hags"],
  },
  {
    id: "gpu.tdr-delay",
    name: "Increase TDR Timeout to 10 Seconds",
    category: "gpu",
    description: "Increase the Timeout Detection and Recovery (TDR) delay from the default 2 seconds to 10 seconds, preventing false GPU resets during heavy load spikes.",
    rationale: "The default 2-second TDR timeout causes false GPU resets during shader compilation, heavy compute loads, or driver transitions. Increasing to 10 seconds prevents unnecessary recovery cycles that manifest as screen flickers or game crashes.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "gpu_reset_frequency",
      directionBetter: "lower",
      estimatedDelta: "Eliminates false TDR resets during load spikes",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers",
        valueName: "TdrDelay",
        valueType: "REG_DWORD",
        newValue: 10,
      },
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers",
        valueName: "TdrDdiDelay",
        valueType: "REG_DWORD",
        newValue: 10,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Genuine GPU hangs will take longer to recover from"],
    tags: ["gpu", "stability", "tdr"],
  },
  {
    id: "gpu.msi-mode",
    name: "Enable GPU MSI (Message Signaled Interrupts) Mode",
    category: "gpu",
    description: "Enable Message Signaled Interrupts for the GPU, replacing legacy line-based interrupts with in-band PCIe messages for lower interrupt latency.",
    rationale: "MSI mode eliminates the need for the GPU to use shared IRQ lines. MSI writes interrupt data directly to memory via PCIe, reducing DPC latency for GPU interrupts. Most modern GPUs support MSI but some drivers default to line-based interrupts.",
    tier: "premium",
    risk: "medium",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "gpu_interrupt_latency",
      directionBetter: "lower",
      estimatedDelta: "~5-15 us reduction in GPU DPC latency",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Enum\\PCI\\<GPU Device ID>\\<Instance>\\Device Parameters\\Interrupt Management\\MessageSignaledInterruptProperties",
        valueName: "MSISupported",
        valueType: "REG_DWORD",
        newValue: 1,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: true,
    sideEffects: ["Requires identifying GPU PCI device path; incorrect path has no effect", "Some older GPUs may not support MSI properly"],
    tags: ["gpu", "latency", "interrupt", "msi"],
  },
  {
    id: "gpu.nvidia-disable-dynamic-pstate",
    name: "Lock NVIDIA GPU to P-State 0 (Maximum Performance)",
    category: "gpu",
    description: "Disable dynamic P-State switching on NVIDIA GPUs by setting DisableDynamicPstate=1, forcing the GPU to remain at maximum clocks at all times.",
    rationale: "NVIDIA GPUs dynamically transition between power states (P0=max, P2=intermediate, P8=idle) based on load. These transitions introduce latency spikes of 5-50ms as the GPU ramps clocks. Locking to P-State 0 eliminates transition latency at the cost of higher idle power and temperatures. This is one of the highest-impact GPU latency tweaks in the redcore lab notes.",
    tier: "premium",
    risk: "medium",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "gpu_clock_transition_latency",
      directionBetter: "lower",
      estimatedDelta: "Eliminates 5-50ms P-State transition spikes",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Control\\Class\\{4d36e968-e325-11ce-bfc1-08002be10318}\\0000",
        valueName: "DisableDynamicPstate",
        valueType: "REG_DWORD",
        newValue: 1,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: true,
    sideEffects: [
      "GPU runs at maximum clocks even at desktop idle",
      "Significantly higher idle power consumption and GPU temperature",
      "Fan noise will increase at idle",
      "NVIDIA-only — AMD GPUs use a different P-State mechanism",
      "Registry path assumes GPU is at adapter index 0000; multi-GPU systems may need 0001",
    ],
    tags: ["gpu", "nvidia", "latency", "pstate", "gaming", "advanced"],
  },
];
