// ─── Power Tuning Module ────────────────────────────────────────────────────
// Derived from the redcore internal power-management notes.

import type { TuningActionDefinition } from "../types.js";

export const powerActions: TuningActionDefinition[] = [
  {
    id: "power.disable-fast-startup",
    name: "Disable Fast Startup (Hybrid Shutdown)",
    category: "power",
    description: "Disable Windows Fast Startup (hybrid shutdown) which hibernates the kernel session instead of performing a full shutdown.",
    rationale: "Fast Startup saves the kernel session to the hibernation file on shutdown, then restores it on boot. This causes stale driver state, prevents clean driver reinitialization, and can lead to hardware initialization issues. A full cold boot ensures all drivers and hardware are cleanly initialized every time.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "driver_initialization_reliability",
      directionBetter: "higher",
      estimatedDelta: "Eliminates stale driver state from hybrid shutdown",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Power",
        valueName: "HiberbootEnabled",
        valueType: "REG_DWORD",
        newValue: 0,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Boot time will be slightly longer (full cold boot instead of hybrid resume)"],
    tags: ["power", "stability", "boot"],
  },
  {
    id: "power.high-performance-plan",
    name: "Activate High Performance Power Plan",
    category: "power",
    description: "Set the active power plan to Windows High Performance (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c), preventing CPU frequency scaling and sleep transitions.",
    rationale: "The Balanced power plan dynamically scales CPU frequency and allows C-state transitions, introducing latency when the CPU must ramp up from a low-power state. High Performance keeps the CPU at maximum frequency and disables most power-saving transitions, ensuring consistent frame times during gaming.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "cpu_frequency_consistency",
      directionBetter: "higher",
      estimatedDelta: "Eliminates frequency scaling latency (~1-5ms wake from C-states)",
      confidence: "measured",
    },
    registryChanges: [],
    serviceChanges: [],
    powerChanges: [
      { settingPath: "SCHEME_CURRENT\\SUB_PROCESSOR\\PROCTHROTTLEMIN", newValue: "100" },
      { settingPath: "SCHEME_CURRENT\\SUB_PROCESSOR\\PROCTHROTTLEMAX", newValue: "100" },
    ],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Higher idle power consumption and heat output", "Laptop battery life significantly reduced"],
    tags: ["power", "performance", "gaming", "latency"],
  },
  {
    id: "power.disable-usb-selective-suspend",
    name: "Disable USB Selective Suspend",
    category: "power",
    description: "Disable USB selective suspend for both AC and DC power, preventing Windows from powering down USB devices during idle periods.",
    rationale: "USB selective suspend saves power by suspending idle USB devices, but causes input latency spikes when mice, keyboards, and controllers must wake from suspended state. This manifests as occasional missed inputs or delayed mouse movements during gaming.",
    tier: "premium",
    risk: "safe",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "usb_input_latency",
      directionBetter: "lower",
      estimatedDelta: "Eliminates USB wake latency spikes (~5-50ms per event)",
      confidence: "measured",
    },
    registryChanges: [],
    serviceChanges: [],
    powerChanges: [
      { settingPath: "2a737441-1930-4402-8d77-b2bebba308a3\\48e6b7a6-50f5-4782-a5d4-53bb8f07e226", newValue: "0" },
    ],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["USB devices remain powered at all times, increasing power draw slightly"],
    tags: ["power", "usb", "input", "latency", "gaming"],
  },
  {
    id: "power.disable-hibernation",
    name: "Disable Hibernation",
    category: "power",
    description: "Disable Windows hibernation, which removes the hibernation file (hiberfil.sys) and prevents the system from saving kernel state to disk on shutdown. Frees disk space equal to approximately 75% of installed RAM.",
    rationale: "Hibernation stores a complete kernel memory snapshot to disk for fast resume. On systems with Fast Startup already disabled, hibernation provides no benefit and consumes significant disk space. Disabling it ensures a clean kernel initialization on every boot and frees gigabytes of disk space on high-RAM systems. On NVMe SSDs, cold boot time is low enough that hibernation resume provides no perceptible advantage.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 7600 },
    dependencies: ["power.disable-fast-startup"],
    conflicts: [],
    estimatedImpact: {
      metric: "available_disk_space",
      directionBetter: "higher",
      estimatedDelta: "Frees ~75% of RAM capacity in disk space (e.g., ~24 GB on a 32 GB system)",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SYSTEM\\CurrentControlSet\\Control\\Power",
        valueName: "HibernateEnabled",
        valueType: "REG_DWORD",
        newValue: 0,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [
      "Hibernate option is removed from the Power menu",
      "Fast Startup will also be disabled as a side effect (both rely on hiberfil.sys)",
      "hiberfil.sys is deleted, freeing significant disk space",
    ],
    tags: ["power", "disk", "boot", "free"],
  },
  {
    id: "power.disable-pcie-link-state-pm",
    name: "Disable PCIe Link State Power Management",
    category: "power",
    description: "Disable Active State Power Management (ASPM) transitions on PCIe devices, preventing the system from placing the PCIe bus in low-power link states (L0s, L1) during idle periods.",
    rationale: "PCIe ASPM transitions power down the PCIe link between the CPU and devices (GPU, NVMe SSD, NIC) to save energy. Re-entering the active state (L0) adds latency — typically 1–10 μs but occasionally manifesting as multi-millisecond stalls under certain driver conditions. Disabling ASPM eliminates this class of intermittent latency spike, which is particularly relevant for GPU render submit and NVMe command dispatch paths.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "pcie_transition_latency",
      directionBetter: "lower",
      estimatedDelta: "Eliminates PCIe link state re-entry latency (1–10 μs typical, up to several ms in pathological cases)",
      confidence: "estimated",
    },
    registryChanges: [],
    serviceChanges: [],
    powerChanges: [
      { settingPath: "501a4d13-42af-4429-9fd1-a8218c268e20/ee12f906-d277-404b-b6da-e5fa1a576df5", newValue: "0" },
    ],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [
      "PCIe devices remain in full-power state at all times, increasing system power draw",
      "Not recommended for laptops where battery life is a priority",
    ],
    tags: ["power", "pcie", "latency", "gaming"],
  },
];
