// ─── redcore-OS Transformation Actions ───────────────────────────────────────
// Deeper than redcore-Tuning: AppX removal, task management, feature cleanup.
// Every action is profile-aware and respects Work PC preservation flags.

import type { TransformAction } from "./transformation.js";

// ─── AppX Bloatware Removal ─────────────────────────────────────────────────

export const APPX_REMOVAL_ACTIONS: TransformAction[] = [
  {
    id: "appx.remove-xbox-apps",
    name: "Remove Xbox Apps",
    category: "cleanup",
    description: "Remove Xbox Game Bar, Xbox Identity Provider, Xbox Speech, and Xbox Game Overlay.",
    rationale: "Xbox UWP apps run background processes even when not actively used. Removing them eliminates background CPU and memory usage from the Xbox ecosystem.",
    risk: "low",
    tier: "free",
    requiresReboot: false,
    reversible: false,
    estimatedSeconds: 15,
    allowedProfiles: "all",
    blockedProfiles: [],
    preservationConflicts: [],
    registryChanges: [],
    serviceChanges: [],
    taskChanges: [],
    appxRemovals: [
      "Microsoft.XboxApp",
      "Microsoft.XboxGameOverlay",
      "Microsoft.XboxGamingOverlay",
      "Microsoft.XboxIdentityProvider",
      "Microsoft.XboxSpeechToTextOverlay",
      "Microsoft.GamingApp",
    ],
    featureChanges: [],
    powerShellCommands: [],
    isDefault: false,
    expertOnly: false,
    atlasEquivalent: null,
    tags: ["cleanup", "xbox", "bloatware"],
    sideEffects: ["Xbox Game Bar overlay will not be available", "Xbox social features removed"],
    warningMessage: null,
  },
  {
    id: "appx.remove-consumer-bloat",
    name: "Remove Consumer Bloatware",
    category: "cleanup",
    description: "Remove pre-installed consumer apps: Clipchamp, News, Weather widget, Solitaire, People, Maps, Feedback Hub.",
    rationale: "Pre-installed consumer apps consume storage, run background tasks, and clutter the Start menu. Most users never use them.",
    risk: "safe",
    tier: "free",
    requiresReboot: false,
    reversible: false,
    estimatedSeconds: 30,
    allowedProfiles: "all",
    blockedProfiles: [],
    preservationConflicts: [],
    registryChanges: [],
    serviceChanges: [],
    taskChanges: [],
    appxRemovals: [
      "Clipchamp.Clipchamp",
      "Microsoft.BingNews",
      "Microsoft.BingWeather",
      "Microsoft.MicrosoftSolitaireCollection",
      "Microsoft.People",
      "Microsoft.WindowsMaps",
      "Microsoft.WindowsFeedbackHub",
      "Microsoft.GetHelp",
      "Microsoft.Getstarted",
      "Microsoft.Todos",
      "Microsoft.549981C3F5F10", // Cortana
      "Microsoft.MixedReality.Portal",
      "Microsoft.SkypeApp",
    ],
    featureChanges: [],
    powerShellCommands: [],
    isDefault: true,
    expertOnly: false,
    atlasEquivalent: null,
    tags: ["cleanup", "bloatware", "appx"],
    sideEffects: ["Removed apps can be reinstalled from Microsoft Store if needed"],
    warningMessage: null,
  },
  {
    id: "appx.remove-widgets",
    name: "Remove Windows Widgets",
    category: "cleanup",
    description: "Remove the Widgets panel and its background web content process.",
    rationale: "The Widgets panel runs a background Edge WebView process that consumes 100-300MB RAM even when the panel is closed.",
    risk: "safe",
    tier: "free",
    requiresReboot: false,
    reversible: false,
    estimatedSeconds: 10,
    allowedProfiles: "all",
    blockedProfiles: [],
    preservationConflicts: [],
    registryChanges: [
      { hive: "HKEY_LOCAL_MACHINE", path: "SOFTWARE\\Policies\\Microsoft\\Dsh", valueName: "AllowNewsAndInterests", valueType: "REG_DWORD", newValue: 0 },
    ],
    serviceChanges: [],
    taskChanges: [],
    appxRemovals: ["MicrosoftWindows.Client.WebExperience"],
    featureChanges: [],
    powerShellCommands: [],
    isDefault: true,
    expertOnly: false,
    atlasEquivalent: null,
    tags: ["cleanup", "widgets", "memory"],
    sideEffects: ["Widgets button removed from taskbar", "News feed no longer available"],
    warningMessage: null,
  },
];

// ─── Scheduled Task Cleanup ─────────────────────────────────────────────────

export const TASK_CLEANUP_ACTIONS: TransformAction[] = [
  {
    id: "tasks.disable-telemetry-tasks",
    name: "Disable Telemetry Scheduled Tasks",
    category: "tasks",
    description: "Disable Microsoft Compatibility Appraiser, Customer Experience Improvement Program, and diagnostic data collection tasks.",
    rationale: "These tasks run periodically in the background, scanning files and uploading telemetry data. Disabling them reduces CPU spikes and network traffic.",
    risk: "safe",
    tier: "free",
    requiresReboot: false,
    reversible: true,
    estimatedSeconds: 5,
    allowedProfiles: "all",
    blockedProfiles: [],
    preservationConflicts: [],
    registryChanges: [],
    serviceChanges: [],
    taskChanges: [
      { taskPath: "\\Microsoft\\Windows\\Application Experience\\Microsoft Compatibility Appraiser", action: "disable" },
      { taskPath: "\\Microsoft\\Windows\\Application Experience\\ProgramDataUpdater", action: "disable" },
      { taskPath: "\\Microsoft\\Windows\\Customer Experience Improvement Program\\Consolidator", action: "disable" },
      { taskPath: "\\Microsoft\\Windows\\Customer Experience Improvement Program\\UsbCeip", action: "disable" },
      { taskPath: "\\Microsoft\\Windows\\DiskDiagnostic\\Microsoft-Windows-DiskDiagnosticDataCollector", action: "disable" },
    ],
    appxRemovals: [],
    featureChanges: [],
    powerShellCommands: [],
    isDefault: true,
    expertOnly: false,
    atlasEquivalent: null,
    tags: ["tasks", "telemetry", "privacy"],
    sideEffects: ["Compatibility assessments will not run", "CEIP data collection stops"],
    warningMessage: null,
  },
  {
    id: "tasks.disable-edge-update-tasks",
    name: "Disable Edge Update Tasks",
    category: "tasks",
    description: "Disable Microsoft Edge update and reporting scheduled tasks.",
    rationale: "Edge update tasks run frequently in the background. Disabling them stops automatic Edge updates (you can still update manually).",
    risk: "low",
    tier: "free",
    requiresReboot: false,
    reversible: true,
    estimatedSeconds: 3,
    allowedProfiles: "all",
    blockedProfiles: ["work_pc"],
    preservationConflicts: [],
    registryChanges: [],
    serviceChanges: [],
    taskChanges: [
      { taskPath: "\\Microsoft\\Edge\\UpdateTaskMachineCore", action: "disable" },
      { taskPath: "\\Microsoft\\Edge\\UpdateTaskMachineUA", action: "disable" },
    ],
    appxRemovals: [],
    featureChanges: [],
    powerShellCommands: [],
    isDefault: false,
    expertOnly: false,
    atlasEquivalent: null,
    tags: ["tasks", "edge", "updates"],
    sideEffects: ["Edge will not auto-update"],
    warningMessage: "Work PC profile blocks this action — managed environments may require Edge updates.",
  },
  {
    id: "tasks.disable-onedrive-tasks",
    name: "Disable OneDrive Scheduled Tasks",
    category: "tasks",
    description: "Disable OneDrive sync startup and reporting tasks.",
    rationale: "OneDrive tasks run at login and periodically, even if OneDrive is not actively used.",
    risk: "safe",
    tier: "free",
    requiresReboot: false,
    reversible: true,
    estimatedSeconds: 3,
    allowedProfiles: "all",
    blockedProfiles: ["work_pc"],
    preservationConflicts: [],
    registryChanges: [],
    serviceChanges: [],
    taskChanges: [
      { taskPath: "\\Microsoft\\OneDrive\\Sync Startup", action: "disable" },
      { taskPath: "\\Microsoft\\OneDrive\\Reporting\\ReportingTaskV2", action: "disable" },
    ],
    appxRemovals: [],
    featureChanges: [],
    powerShellCommands: [],
    isDefault: true,
    expertOnly: false,
    atlasEquivalent: null,
    tags: ["tasks", "onedrive", "sync"],
    sideEffects: ["OneDrive will not auto-start at login"],
    warningMessage: "Work PC profile blocks this — OneDrive may be required for business file sync.",
  },
];

// ─── Work PC Preservation Actions ───────────────────────────────────────────

export const WORK_PC_PRESERVATION: TransformAction[] = [
  {
    id: "preservation.verify-work-services",
    name: "Verify Work-Critical Services",
    category: "preservation",
    description: "Verify that printing, RDP, SMB, DNS, DHCP, and domain services are running and properly configured.",
    rationale: "Before any transformation, verify that business-critical services are healthy. This creates a baseline for preservation validation after transformation.",
    risk: "safe",
    tier: "free",
    requiresReboot: false,
    reversible: true,
    estimatedSeconds: 10,
    allowedProfiles: ["work_pc"],
    blockedProfiles: [],
    preservationConflicts: [],
    registryChanges: [],
    serviceChanges: [],
    taskChanges: [],
    appxRemovals: [],
    featureChanges: [],
    powerShellCommands: [],
    isDefault: true,
    expertOnly: false,
    atlasEquivalent: null,
    tags: ["preservation", "work_pc", "validation"],
    sideEffects: [],
    warningMessage: null,
  },
];
