// Privacy & Telemetry Module
// Derived from the redcore internal privacy-hardening notes.

import type { TuningActionDefinition } from "../types.js";

export const privacyActions: TuningActionDefinition[] = [
  {
    id: "privacy.disable-telemetry",
    name: "Disable Windows Telemetry",
    category: "privacy",
    description: "Set telemetry level to Security (0) and disable Connected User Experiences and Telemetry service.",
    rationale: "Windows telemetry collects diagnostic data and sends it to Microsoft. Disabling it reduces background network activity and improves privacy.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 10240 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "background_network_activity",
      directionBetter: "lower",
      estimatedDelta: "Reduced background data transmission",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection",
        valueName: "AllowTelemetry",
        valueType: "REG_DWORD",
        newValue: 0,
      },
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection",
        valueName: "AllowTelemetry",
        valueType: "REG_DWORD",
        newValue: 0,
      },
    ],
    serviceChanges: [
      { serviceName: "DiagTrack", newStartType: "Disabled" },
      { serviceName: "dmwappushservice", newStartType: "Disabled" },
    ],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Windows diagnostic reports won't be collected", "Some Microsoft feedback features may not work"],
    tags: ["privacy", "telemetry", "debloat"],
  },
  {
    id: "privacy.disable-advertising-id",
    name: "Disable Advertising ID",
    category: "privacy",
    description: "Prevent apps from using your advertising ID for cross-app personalized advertising.",
    rationale: "The advertising ID tracks user behavior across apps. Disabling it reduces profiling without any performance impact.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 10240 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      {
        hive: "HKEY_CURRENT_USER",
        path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\AdvertisingInfo",
        valueName: "Enabled",
        valueType: "REG_DWORD",
        newValue: 0,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [],
    tags: ["privacy"],
  },
  {
    id: "privacy.disable-ceip",
    name: "Disable Customer Experience Improvement Program",
    category: "privacy",
    description: "Opt out of the Windows Customer Experience Improvement Program data collection.",
    rationale: "CEIP collects usage data for Microsoft. Disabling it reduces background data collection tasks.",
    tier: "free",
    risk: "safe",
    compatibility: {},
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Policies\\Microsoft\\SQMClient\\Windows",
        valueName: "CEIPEnable",
        valueType: "REG_DWORD",
        newValue: 0,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [],
    tags: ["privacy", "telemetry"],
  },
  {
    id: "privacy.disable-cloud-content",
    name: "Disable Cloud Content & Suggestions",
    category: "privacy",
    description: "Disable Windows Spotlight, suggested apps, tips, and cloud-delivered content.",
    rationale: "Cloud content features download and display promotional material, consuming bandwidth and creating visual noise.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 10240 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent",
        valueName: "DisableWindowsConsumerFeatures",
        valueType: "REG_DWORD",
        newValue: 1,
      },
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent",
        valueName: "DisableSoftLanding",
        valueType: "REG_DWORD",
        newValue: 1,
      },
      {
        hive: "HKEY_CURRENT_USER",
        path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager",
        valueName: "SilentInstalledAppsEnabled",
        valueType: "REG_DWORD",
        newValue: 0,
      },
      {
        hive: "HKEY_CURRENT_USER",
        path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager",
        valueName: "SystemPaneSuggestionsEnabled",
        valueType: "REG_DWORD",
        newValue: 0,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["No more app suggestions on Start menu", "No Windows Spotlight on lock screen"],
    tags: ["privacy", "debloat", "cleanup"],
  },
  {
    id: "privacy.disable-error-reporting",
    name: "Disable Windows Error Reporting",
    category: "privacy",
    description: "Disable automatic error reporting to Microsoft.",
    rationale: "Error reporting sends crash dumps to Microsoft. Disabling reduces background uploads. Note: this may make debugging harder if you encounter system issues.",
    tier: "free",
    risk: "safe",
    compatibility: {},
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Error Reporting",
        valueName: "Disabled",
        valueType: "REG_DWORD",
        newValue: 1,
      },
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Microsoft\\Windows\\Windows Error Reporting",
        valueName: "Disabled",
        valueType: "REG_DWORD",
        newValue: 1,
      },
    ],
    serviceChanges: [
      { serviceName: "WerSvc", newStartType: "Disabled" },
    ],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Crash reports won't be sent to Microsoft", "Some automatic fixes may not be applied"],
    tags: ["privacy", "telemetry"],
  },
  {
    id: "privacy.disable-clipboard-history",
    name: "Disable Clipboard History & Cloud Sync",
    category: "privacy",
    description: "Disable Windows clipboard history and cross-device clipboard synchronization.",
    rationale: "Clipboard history stores copied content and can sync it across devices via Microsoft account. Disabling prevents clipboard data from being stored beyond the current copy and eliminates cloud transmission of sensitive copied content.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 17763 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Policies\\Microsoft\\Windows\\System",
        valueName: "AllowClipboardHistory",
        valueType: "REG_DWORD",
        newValue: 0,
      },
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Policies\\Microsoft\\Windows\\System",
        valueName: "AllowCrossDeviceClipboard",
        valueType: "REG_DWORD",
        newValue: 0,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Win+V clipboard history panel will be empty", "Cloud clipboard sync across devices will stop"],
    tags: ["privacy", "clipboard", "sync"],
  },
  {
    id: "privacy.disable-activity-feed",
    name: "Disable Activity History & Timeline",
    category: "privacy",
    description: "Disable Windows activity feed, timeline, and activity data uploads to Microsoft.",
    rationale: "Windows Activity History tracks app usage, file opens, and browsing history for Timeline features. Disabling prevents local collection and cloud upload of activity data, improving privacy without affecting system functionality.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 17134 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Policies\\Microsoft\\Windows\\System",
        valueName: "EnableActivityFeed",
        valueType: "REG_DWORD",
        newValue: 0,
      },
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Policies\\Microsoft\\Windows\\System",
        valueName: "PublishUserActivities",
        valueType: "REG_DWORD",
        newValue: 0,
      },
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Policies\\Microsoft\\Windows\\System",
        valueName: "UploadUserActivities",
        valueType: "REG_DWORD",
        newValue: 0,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Windows Timeline (Win+Tab history) will be empty", "Activity-based Cortana suggestions will stop"],
    tags: ["privacy", "telemetry", "timeline"],
  },
  {
    id: "privacy.disable-typing-insights",
    name: "Disable Typing Insights & Inking Data",
    category: "privacy",
    description: "Disable collection of typing patterns, inking data, and linguistic data sent to Microsoft.",
    rationale: "Windows collects typing patterns and handwriting data to improve input prediction. Disabling prevents this data from being collected locally or transmitted to Microsoft servers.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 17134 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      {
        hive: "HKEY_CURRENT_USER",
        path: "SOFTWARE\\Microsoft\\input\\Settings",
        valueName: "InsightsEnabled",
        valueType: "REG_DWORD",
        newValue: 0,
      },
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\TextInput",
        valueName: "AllowLinguisticDataCollection",
        valueType: "REG_DWORD",
        newValue: 0,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Typing prediction accuracy may be slightly reduced"],
    tags: ["privacy", "telemetry", "typing"],
  },
  {
    id: "privacy.disable-search-suggestions",
    name: "Disable Search Suggestions & Web Results",
    category: "privacy",
    description: "Disable Cortana and web search suggestions in Windows Search, keeping search local-only.",
    rationale: "Windows Search sends keystrokes to Bing for web suggestions, creating both a privacy concern and unnecessary network traffic. Disabling makes search local-only, which is faster and more private.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 10240 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search",
        valueName: "AllowCortana",
        valueType: "REG_DWORD",
        newValue: 0,
      },
      {
        hive: "HKEY_CURRENT_USER",
        path: "SOFTWARE\\Policies\\Microsoft\\Windows\\Explorer",
        valueName: "DisableSearchBoxSuggestions",
        valueType: "REG_DWORD",
        newValue: 1,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["No web results in Start menu search", "Cortana features will be disabled"],
    tags: ["privacy", "search", "cortana"],
  },
];
