// ─── Startup & Background Tuning Module ─────────────────────────────────────
// Derived from PC-Tuning registry-options.json and bloatware-removal skill.

import type { TuningActionDefinition } from "../types.js";

export const startupActions: TuningActionDefinition[] = [
  {
    id: "startup.disable-background-apps",
    name: "Disable Background Apps",
    category: "startup",
    description: "Prevent UWP/Store apps from running in the background by setting the LetAppsRunInBackground policy to 2 (force deny).",
    rationale: "Windows allows UWP apps to execute background tasks for notifications, updates, and tile refreshes. These consume CPU, memory, and network resources. Setting LetAppsRunInBackground to 2 (force deny) prevents all UWP apps from running background tasks, freeing resources for gaming.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 10240 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "background_cpu_usage",
      directionBetter: "lower",
      estimatedDelta: "Reduces idle CPU usage by ~1-5%",
      confidence: "estimated",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy",
        valueName: "LetAppsRunInBackground",
        valueType: "REG_DWORD",
        newValue: 2,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [
      "UWP app notifications may be delayed or not received",
      "Store apps will not update live tiles",
      "Alarms & Clock app background alarms may not fire",
    ],
    tags: ["startup", "debloat", "performance", "uwp"],
  },
  {
    id: "startup.disable-automatic-maintenance",
    name: "Disable Automatic Maintenance",
    category: "startup",
    description: "Disable Windows Automatic Maintenance which runs scheduled tasks including disk defragmentation, Windows Update checks, and security scans during idle periods.",
    rationale: "Automatic Maintenance activates during what Windows considers idle time, but its definition of idle can overlap with gaming sessions (especially during loading screens or low-GPU moments). The maintenance tasks cause sudden CPU, disk, and network spikes that produce frame time stutter.",
    tier: "free",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "background_task_interference",
      directionBetter: "lower",
      estimatedDelta: "Eliminates maintenance-induced I/O and CPU spikes",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\Maintenance",
        valueName: "MaintenanceDisabled",
        valueType: "REG_DWORD",
        newValue: 1,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: [
      "Disk optimization (TRIM for SSDs) must be run manually",
      "Windows Defender scheduled scans will not run automatically",
    ],
    tags: ["startup", "maintenance", "debloat", "performance"],
  },
  {
    id: "startup.disable-autoplay",
    name: "Disable AutoPlay and AutoRun",
    category: "startup",
    description: "Disable AutoPlay for all drive types and disable AutoRun, preventing automatic program execution when media is inserted.",
    rationale: "AutoPlay and AutoRun automatically execute programs or open handlers when removable media, network drives, or optical discs are connected. This is both a security risk (malware autorun vectors) and a source of unwanted background activity. Disabling both hardens the system and prevents unwanted process spawning.",
    tier: "free",
    risk: "safe",
    compatibility: {},
    dependencies: [],
    conflicts: [],
    estimatedImpact: null,
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer",
        valueName: "NoDriveTypeAutoRun",
        valueType: "REG_DWORD",
        newValue: 255,
      },
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer",
        valueName: "NoAutorun",
        valueType: "REG_DWORD",
        newValue: 1,
      },
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer",
        valueName: "NoAutoplayfornonVolume",
        valueType: "REG_DWORD",
        newValue: 1,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["USB drives and optical discs will not automatically open when inserted"],
    tags: ["startup", "security", "autoplay"],
  },
  {
    id: "startup.disable-gamebar-presence",
    name: "Disable GameBarPresenceWriter",
    category: "startup",
    description: "Disable the GameBarPresenceWriter background process that runs alongside every game, even when Game Bar overlay is not used.",
    rationale: "GameBarPresenceWriter is a COM-activated background process that monitors game presence for Xbox social features. It runs for every DirectX application regardless of whether Game Bar is actively used, consuming CPU cycles and creating periodic wake-ups. Disabling its activation type prevents it from launching.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 10240 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "background_process_count",
      directionBetter: "lower",
      estimatedDelta: "Eliminates 1 background process per game session",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Microsoft\\WindowsRuntime\\ActivatableClassId\\Windows.Gaming.GameBar.PresenceServer.Internal.PresenceWriter",
        valueName: "ActivationType",
        valueType: "REG_DWORD",
        newValue: 0,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Xbox social presence features will not show 'Currently Playing' status"],
    tags: ["startup", "gaming", "debloat", "performance"],
  },
  {
    id: "startup.disable-cloud-notifications",
    name: "Disable Cloud Notification Network Usage",
    category: "startup",
    description: "Block Windows Push Notification System from making network calls to Microsoft cloud servers for notification delivery.",
    rationale: "The Windows Push Notification service (WNS) maintains persistent connections to Microsoft servers for cloud-based notifications. This creates background network activity and periodic CPU wake-ups. Blocking cloud notifications eliminates this traffic while local app notifications continue to work.",
    tier: "free",
    risk: "safe",
    compatibility: { minBuild: 9200 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "background_network_connections",
      directionBetter: "lower",
      estimatedDelta: "Eliminates persistent WNS cloud connection",
      confidence: "measured",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Policies\\Microsoft\\Windows\\CurrentVersion\\PushNotifications",
        valueName: "NoCloudApplicationNotification",
        valueType: "REG_DWORD",
        newValue: 1,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: false,
    sideEffects: ["Cloud-delivered notifications (e.g., from Microsoft 365) will not appear"],
    tags: ["startup", "privacy", "network", "debloat"],
  },
  {
    id: "startup.disable-fault-tolerant-heap",
    name: "Disable Fault Tolerant Heap",
    category: "startup",
    description: "Disable the Fault Tolerant Heap (FTH) which automatically applies runtime mitigations to applications that crash repeatedly.",
    rationale: "FTH monitors application crashes and silently applies heap mitigations (guard pages, delayed frees) to prevent repeat crashes. These mitigations add memory overhead and can mask real bugs. For a tuned gaming system, FTH's runtime patching introduces unnecessary overhead. Disabling it keeps applications running with their intended memory behavior.",
    tier: "premium",
    risk: "low",
    compatibility: { minBuild: 7600 },
    dependencies: [],
    conflicts: [],
    estimatedImpact: {
      metric: "heap_allocation_overhead",
      directionBetter: "lower",
      estimatedDelta: "Eliminates FTH guard page overhead on affected applications",
      confidence: "estimated",
    },
    registryChanges: [
      {
        hive: "HKEY_LOCAL_MACHINE",
        path: "SOFTWARE\\Microsoft\\FTH",
        valueName: "Enabled",
        valueType: "REG_DWORD",
        newValue: 0,
      },
    ],
    serviceChanges: [],
    powerChanges: [],
    bcdChanges: [],
    requiresReboot: true,
    sideEffects: [
      "Applications that previously crashed may crash again instead of being silently mitigated",
      "This is usually desirable — FTH masks bugs rather than fixing them",
    ],
    tags: ["startup", "performance", "memory", "advanced"],
  },
];
